[book]
authors = ["Jia Yuekai, Zhou Yi, Xie Kaizhi, YU Chen"]
language = "cn"
multilingual = false
src = "src"
title = "Arceos Tutorial Book"
[rust]
edition = "2021"
[output.html.playpen]
editable = true
[output.html]
git-repository-url = "https://github.com/rcore-os/arceos-tutorial-book"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
# mathjax-support = true
# [preprocessor.mathjax]
# renderers = ["html"]
[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
